// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBuldiXiswHd739lb0-S43sDiPwrW40gtA',
    appId: '1:992353345526:web:42e92900ab195b4198f1d7',
    messagingSenderId: '992353345526',
    projectId: 'ecommerce-37962',
    authDomain: 'ecommerce-37962.firebaseapp.com',
    storageBucket: 'ecommerce-37962.firebasestorage.app',
    measurementId: 'G-330YM0KD8V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrafzSK-HC8oq28l1ZhUEN_aKKvU7mgdk',
    appId: '1:992353345526:android:c8820f6a888fac8198f1d7',
    messagingSenderId: '992353345526',
    projectId: 'ecommerce-37962',
    storageBucket: 'ecommerce-37962.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1V8-J3BugcugSH3MlozU4ReAz-CnVhvY',
    appId: '1:992353345526:ios:7951c1d9455a633098f1d7',
    messagingSenderId: '992353345526',
    projectId: 'ecommerce-37962',
    storageBucket: 'ecommerce-37962.firebasestorage.app',
    iosBundleId: 'com.example.commerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1V8-J3BugcugSH3MlozU4ReAz-CnVhvY',
    appId: '1:992353345526:ios:7951c1d9455a633098f1d7',
    messagingSenderId: '992353345526',
    projectId: 'ecommerce-37962',
    storageBucket: 'ecommerce-37962.firebasestorage.app',
    iosBundleId: 'com.example.commerceapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBuldiXiswHd739lb0-S43sDiPwrW40gtA',
    appId: '1:992353345526:web:8bdc60731f7a282298f1d7',
    messagingSenderId: '992353345526',
    projectId: 'ecommerce-37962',
    authDomain: 'ecommerce-37962.firebaseapp.com',
    storageBucket: 'ecommerce-37962.firebasestorage.app',
    measurementId: 'G-36MWTZYMF6',
  );
}
